name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          g++ -o contact_manager main.cpp name.cpp address.cpp contact.cpp
      - name: Run
        run: ./contact_manager
